import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
    Map as MapIcon,
    GraduationCap,
    Mic,
    LayoutDashboard
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { toast } from 'sonner';
import { MOCK_BLOCK_DATA } from '@/lib/rpAnalytics';
import { MentorCopilot } from '@/components/rp/MentorCopilot';
import { SpaceScene } from '@/components/layout/SpaceScene';
import { CRPDashboard } from '@/components/rp/CRPDashboard';
import { ARPDashboard } from '@/components/rp/ARPDashboard';
import { BRPDashboard } from '@/components/rp/BRPDashboard';
import { LanguageSwitcher } from '@/components/common/LanguageSwitcher';
import { jsPDF } from 'jspdf';

type RPRole = 'BRP' | 'CRP' | 'ARP';

export default function ResourcePersonDashboard() {
    const [role, setRole] = useState<RPRole>('BRP');
    const [selectedCluster, setSelectedCluster] = useState(MOCK_BLOCK_DATA.clusters[0]);
    const [showMentorCopilot, setShowMentorCopilot] = useState(false);
    const [isExporting, setIsExporting] = useState(false);

    const triggerDownload = (fileName: string, content: string, title: string) => {
        const doc = new jsPDF();

        // Header
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(22);
        doc.setTextColor(0, 102, 204);
        doc.text('SHIKSHALOKAM RESOURCE COMMAND CENTER', 20, 20);

        doc.setLineWidth(0.5);
        doc.line(20, 25, 190, 25);

        // Report Info
        doc.setFontSize(16);
        doc.setTextColor(0, 0, 0);
        doc.text(title, 20, 40);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(12);
        doc.text(`Role: ${role}`, 20, 50);
        doc.text(`Cluster: ${selectedCluster.name}`, 20, 57);
        doc.text(`Date: ${new Date().toLocaleString()}`, 20, 64);

        // Body
        doc.setFont('helvetica', 'bold');
        doc.setFontSize(14);
        doc.text('Summary of Analytics:', 20, 80);

        doc.setFont('helvetica', 'normal');
        doc.setFontSize(11);
        const splitText = doc.splitTextToSize(content, 170);
        doc.text(splitText, 20, 90);

        // Footer
        doc.setFontSize(10);
        doc.setTextColor(150, 150, 150);
        doc.text('Generated by Resource Intelligence Engine v2.0 - Strictly Confidential', 20, 280);

        doc.save(fileName);
    };

    const handleGenerateReport = () => {
        setIsExporting(true);
        const reportType = role === 'BRP' ? 'Block Deployment Report' : role === 'ARP' ? 'Academic Mastery Analytics' : 'Field Visit Log';
        const fileName = `${role}_Report_${selectedCluster.name.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;

        const getRoleSpecificContent = () => {
            switch (role) {
                case 'BRP':
                    return `This is a synthesized Block Operations Report for ${selectedCluster.name}. 
                    
ADMINISTRATIVE SUMMARY:
- Personnel Deployment: The cluster is currently at ${selectedCluster.overallHealth}% staffing efficiency.
- Infrastructure Status: ${selectedCluster.needsSupportCount} schools have flagged critical maintenance requirements.
- Compliance: MDM and UDISE verification is at 88% completion for the current quarter.
                    
RECOMMENDATION:
Prioritize the transfer of 2 surplus teachers to schools in the western sector to balance the Pupil-Teacher Ratio (PTR).`;
                case 'ARP':
                    return `This is a synthesized Academic Mastery Analytics report for ${selectedCluster.name}.
                    
PEDAGOGICAL INSIGHTS:
- Concept Mastery: Grade 7 Math (Fractions) remains a cluster-wide gap with <45% mastery.
- Training Impact: The recent 'Experiential Science' workshop has improved classroom engagement by 15%.
- Resource Usage: Top performing school, ${selectedCluster.topPerformingSchool}, shows 92% utilization of digital library kits.
                    
RECOMMENDATION:
Conduct a diagnostic remediation session for Grade 7 teachers focusing on visual aids for abstract mathematical concepts.`;
                case 'CRP':
                    return `This is a synthesized Field Visit & Observation Log for ${selectedCluster.name}.
                    
FIELD SUMMARY:
- Visit Velocity: 12 schools visited this month with an average observation score of 72%.
- Classroom Management: Significant improvement noted in 'Student Voice' and interactive questioning techniques.
- Peer Mentorship: 2 new 'Math Circle' peer groups established across schools in the northern zone.
                    
RECOMMENDATION:
Schedule a follow-up visit to the underperforming schools to reassess the implementation of the NIPUN Bharat pedagogical guidelines.`;
                default:
                    return `Synthesized report for ${selectedCluster.name}. All data is synchronized with the Resource Central Repository.`;
            }
        };

        toast.promise(
            new Promise((resolve) => setTimeout(resolve, 2500)),
            {
                loading: `Synthesizing ${reportType} for ${selectedCluster.name}...`,
                success: () => {
                    setIsExporting(false);
                    const mockContent = getRoleSpecificContent();
                    triggerDownload(fileName, mockContent, reportType);
                    return `${reportType} for ${selectedCluster.name} has been generated.`;
                },
                error: () => {
                    setIsExporting(false);
                    return 'Infrastructure error: Failed to generate report.';
                },
            }
        );
    };

    return (
        <div className="min-h-screen bg-slate-50 dark:bg-[#020617] relative overflow-x-hidden p-6 md:p-10 selection:bg-brand-blue/30 font-sans text-slate-900 dark:text-slate-100 transition-colors duration-300">
            <div className="fixed inset-0 z-0 pointer-events-none">
                <div className="hidden dark:block">
                    <SpaceScene />
                    <div className="absolute inset-0 bg-gradient-to-b from-transparent via-[#020617]/80 to-[#020617]" />
                </div>
                <div className="dark:hidden absolute inset-0 bg-slate-50 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-blue-100 via-transparent to-transparent opacity-40" />
            </div>

            <div className="max-w-7xl mx-auto relative z-10 space-y-8">
                {/* Header Section */}
                <div className="flex flex-col xl:flex-row xl:items-end justify-between gap-8 pb-8 border-b border-slate-200 dark:border-white/5">
                    <div className="space-y-2">
                        <div className="flex items-center gap-3">
                            <div className="relative">
                                <div className="absolute inset-0 bg-brand-blue/40 blur-xl rounded-full animate-pulse" />
                                <div className="w-14 h-14 rounded-2xl bg-gradient-to-br from-brand-blue to-blue-600 flex items-center justify-center relative shadow-[0_0_30px_rgba(37,99,235,0.3)] border border-white/10">
                                    <LayoutDashboard className="w-7 h-7 text-white" />
                                </div>
                            </div>
                            <div className="space-y-0.5">
                                <h1 className="text-4xl md:text-5xl font-black font-orbitron tracking-tighter text-slate-900 dark:text-white uppercase drop-shadow-2xl">
                                    Resource <span className="text-transparent bg-clip-text bg-gradient-to-r from-brand-blue to-cyan-400">Command</span>
                                </h1>
                                <p className="text-slate-400 text-sm font-medium tracking-wide flex items-center gap-2">
                                    <span className="w-2 h-2 rounded-full bg-green-500 animate-pulse" />
                                    OPERATIONAL DASHBOARD v2.0 • {MOCK_BLOCK_DATA.name.toUpperCase()} (BIDAR)
                                </p>
                            </div>
                        </div>
                    </div>
                    <div className="flex items-center gap-4">
                        <select
                            value={selectedCluster.id}
                            onChange={(e) => {
                                const cluster = MOCK_BLOCK_DATA.clusters.find(c => c.id === e.target.value);
                                if (cluster) setSelectedCluster(cluster);
                            }}
                            className="bg-white/50 dark:bg-slate-900/50 border border-slate-200 dark:border-white/10 rounded-xl px-4 py-2 text-sm font-bold focus:outline-none focus:ring-2 focus:ring-brand-blue"
                        >
                            {MOCK_BLOCK_DATA.clusters.map(c => (
                                <option key={c.id} value={c.id}>{c.name} Cluster</option>
                            ))}
                        </select>
                        <LanguageSwitcher />
                    </div>
                </div>

                {/* Role Switcher - HUD Style */}
                <div className="flex p-2 bg-white/90 dark:bg-slate-900/80 backdrop-blur-2xl rounded-2xl border border-slate-200 dark:border-white/10 shadow-[0_15px_35px_-10px_rgba(0,0,0,0.05)] relative overflow-hidden ring-1 ring-slate-200/50 dark:ring-white/5 max-w-2xl">
                    <div className="absolute inset-x-0 -top-full h-full bg-gradient-to-b from-slate-100/50 dark:from-white/5 to-transparent opacity-20" />
                    {(['BRP', 'ARP', 'CRP'] as RPRole[]).map((r) => (
                        <button
                            key={r}
                            onClick={() => setRole(r)}
                            className={`
                                    flex-1 relative px-8 py-3.5 rounded-xl text-xs font-black uppercase tracking-[0.2em] transition-all duration-500 ease-out
                                    ${role === r
                                    ? 'text-white shadow-[0_10px_25px_-5px_rgba(59,130,246,0.4)] bg-gradient-to-br from-brand-blue via-blue-600 to-blue-700 transform scale-[1.02] z-10'
                                    : 'text-slate-500 hover:text-slate-900 dark:hover:text-slate-300 hover:bg-slate-50 dark:hover:bg-white/5'
                                }
                                `}
                        >
                            {r} View
                            {role === r && (
                                <div className="absolute inset-0 bg-gradient-to-t from-black/10 to-transparent pointer-events-none rounded-xl" />
                            )}
                        </button>
                    ))}
                </div>

                {/* Main Content Area */}
                <div className="w-full">
                    <div className="bg-white/90 dark:bg-[#0A0F1E]/40 border border-slate-200/60 dark:border-white/5 rounded-3xl p-1 md:p-8 backdrop-blur-xl relative overflow-hidden min-h-[600px] shadow-[0_20px_50px_-20px_rgba(0,0,0,0.1)] dark:shadow-none">
                        <div className="absolute inset-0 bg-gradient-to-tr from-slate-50/50 via-transparent to-blue-50/30 pointer-events-none dark:hidden" />

                        {/* Dashboard Role Context Header */}
                        <div className="flex flex-col md:flex-row md:items-end justify-between mb-8 pb-6 border-b border-slate-200 dark:border-white/5 gap-4 relative z-10">
                            <div>
                                <h2 className="text-3xl font-black text-slate-800 dark:text-white flex items-center gap-3 tracking-tighter uppercase">
                                    {role === 'CRP' ? (
                                        <div className="p-2.5 bg-brand-blue/10 dark:bg-brand-blue/20 rounded-xl text-brand-blue shadow-sm"><MapIcon className="w-6 h-6" /></div>
                                    ) : role === 'ARP' ? (
                                        <div className="p-2.5 bg-pink-500/10 dark:bg-pink-500/20 rounded-xl text-pink-500 shadow-sm"><GraduationCap className="w-6 h-6" /></div>
                                    ) : (
                                        <div className="p-2.5 bg-purple-500/10 dark:bg-purple-500/20 rounded-xl text-purple-500 shadow-sm"><LayoutDashboard className="w-6 h-6" /></div>
                                    )}
                                    <span className="bg-clip-text text-transparent bg-gradient-to-r from-slate-900 via-slate-700 to-slate-800 dark:from-white dark:to-slate-400">
                                        {role === 'BRP' ? 'Block Operations Center' :
                                            role === 'ARP' ? 'Academic Excellence Hub' :
                                                'Field Mentor Cockpit'}
                                    </span>
                                </h2>
                                <p className="text-slate-500 dark:text-slate-400 text-sm mt-3 ml-14 font-medium max-w-2xl leading-relaxed italic border-l-2 border-slate-100 dark:border-white/5 pl-4">
                                    {role === 'BRP' ? 'Administrative oversight, resource allocation, and compliance monitoring across all clusters.' :
                                        role === 'ARP' ? 'Pedagogical planning, teacher training analytics, and learning outcome tracking.' :
                                            'Daily visit planning, classroom observation tools, and peer mentorship management.'}
                                </p>
                            </div>
                            <div className="flex items-center gap-3 ml-14 md:ml-0 relative z-10">
                                <Button
                                    size="lg"
                                    disabled={isExporting}
                                    className="bg-slate-900 text-white hover:bg-slate-800 dark:bg-white dark:text-black dark:hover:bg-slate-200 font-bold uppercase tracking-wider text-xs h-12 px-8 shadow-[0_10px_20px_-5px_rgba(0,0,0,0.3)] dark:shadow-white/10 transition-all flex items-center gap-2 rounded-xl"
                                    onClick={handleGenerateReport}
                                >
                                    {isExporting ? <div className="w-4 h-4 border-2 border-current border-t-transparent rounded-full animate-spin" /> : <div className="w-2 h-2 rounded-full bg-blue-400 animate-ping" />}
                                    Export {role} Report
                                </Button>
                                <Button
                                    size="icon"
                                    className="h-12 w-12 rounded-xl bg-white text-slate-500 hover:bg-slate-50 hover:text-slate-900 dark:bg-slate-800 dark:text-slate-300 dark:hover:bg-slate-700 dark:hover:text-white border border-slate-200 dark:border-white/5 shadow-sm"
                                    onClick={() => setShowMentorCopilot(true)}
                                >
                                    <Mic className="w-5 h-5" />
                                </Button>
                            </div>
                        </div>

                        {/* Dynamic Dashboard Content */}
                        <AnimatePresence mode="wait">
                            <motion.div
                                key={role + selectedCluster.id}
                                initial={{ opacity: 0, y: 20 }}
                                animate={{ opacity: 1, y: 0 }}
                                exit={{ opacity: 0, y: -20 }}
                                transition={{ duration: 0.3 }}
                                className="w-full"
                            >
                                {role === 'CRP' && <CRPDashboard cluster={selectedCluster} />}
                                {role === 'ARP' && <ARPDashboard cluster={selectedCluster} />}
                                {role === 'BRP' && <BRPDashboard cluster={selectedCluster} />}
                            </motion.div>
                        </AnimatePresence>
                    </div>
                </div>
            </div >

            <AnimatePresence>
                {showMentorCopilot && (
                    <MentorCopilot onClose={() => setShowMentorCopilot(false)} />
                )}
            </AnimatePresence>
        </div >
    );
}
